### ISSUE TITLE
Fixes

### ISSUE THREAD

**Issue by jah2488** [rcantu1234/Ruby_AgeVerifier#2]
- Currently Pigatize does not work in javascript. It always assumes the word starts with a vowel. Your function that checks of a word starts with a vowel is not working correctly.
- Fizzbuzz in javascript does not work, because your `Fizzbuzz` function does not take any parameters.

**Comment by rcantu1234** [comment]
Could you please take a look at Fizzbuzz.js because I believe that it is fixed?  I could not get pigatize to work because it is giving me this error:   var text = prompt("Please enter a word and I will translate to pig latin: “).  If you could let me know the problem for that error I will continue on it if not I will come back to it.

**Comment by jah2488** [comment]
@rcantu1234 Fizzbuzz is still broken because your function does not take any parameters. 

I don't get that error when I run your pigatize in the browser.

**Comment by rcantu1234** [comment]
I believe that pigatize.js is fixed.  Fizz buzz works fine for me.  15, 30, and 45 are the only numbers that take 3 and 5 without a remainder with a parameter of 50.  Does that sound correct?
